# Generated by Django 2.1.3 on 2018-11-27 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('idarticulo', models.AutoField(max_length=20, primary_key=True, serialize=False)),
                ('Cantidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('NumeroFactura', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('nitEmpresa', models.CharField(max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idCliente', models.CharField(max_length=50)),
                ('Nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('total', models.CharField(max_length=50)),
                ('mediopago', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Cantidad', models.CharField(max_length=20)),
                ('Precio', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('Cedula', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='cedula_v',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='polls.Vendedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='idarticulo',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.articulo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='idProducto',
            field=models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='polls.Producto'),
        ),
    ]
