# Generated by Django 2.1.3 on 2018-11-20 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='User',
            new_name='Nombre',
        ),
    ]
