# Generated by Django 2.1.3 on 2018-11-21 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_cliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
