# Generated by Django 2.1.3 on 2018-11-21 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20181121_0525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='second_last_name',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='second_name',
        ),
    ]
